version: '3.1'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - quizme-data:/var/lib/postgresql/data

  frontend:
    image: quizmefront
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: quizmebackend
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres

volumes:
  quizme-data:
    external: true
